### PR TITLE
Update Dockerfile to buster-slim

### PR DESCRIPTION
**Pull request by snoopotic**
I think for the testing purpose the slim base is worth trying. :)

### CODE REVIEW

**Comment by geerlingguy** [comment]
Do you know the size difference between buster and buster-slim?

**Comment by snoopotic** [comment]
well, it's not that big difference but is is one. Just built them: 

REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
geerlingguy/docker-debian10-ansible   slim                8d63e5cb0e69        2 minutes ago       580MB
geerlingguy/docker-debian10-ansible   latest              e9c21b0734ff        4 minutes ago       644MB

**Comment by fourstepper** [comment]
Where does the size difference come from?

**Comment by martialblog** [comment]
Hi, 

I just did some tests with the buster-slim Base, the final Image is 64MB smaller. Not much, but still good. 

```
geerlingguy/docker-debian10-ansible      latest   f05854a47f88   7 days ago       900MB
geerlingguy/docker-debian10-ansible        slim   51d10b9f9bb9   42 seconds ago   836MB
```

Where the size difference comes from:

> These tags are an experiment in providing a slimmer base (removing some extra files that are normally not necessary within containers, such as man pages and documentation), and are definitely subject to change. - https://hub.docker.com/_/debian

**Comment by geerlingguy** [comment]
Good to save a little bandwidth here and there.

I'm going to merge this and _hopefully_ it doesn't result in a lot of breakage (you may laugh, but some tools barf when docs and the like aren't in the expected places...).

If it does, may pull it back.

**Comment by geerlingguy** [comment]
Heh... this did break Java installs inside the container, as that relies on `man` having a certain folder present. See https://github.com/geerlingguy/ansible-role-java/issues/64

I just added another commit to make sure that folder is present so I don't have to add it in downstream roles: https://github.com/geerlingguy/docker-debian10-ansible/commit/4b6076ce3e8cfa9317aa1fec3e9ab68c035baf75

**Comment by fourstepper** [comment]
@geerlingguy @snoopotic  Can we revert this?

Reasoning: 

1) We are trying to simulate real-world Debian systems - `buster:slim` is hardly closer to what the majority of people are running as their production Debian systems.
2) It has broken the above Java installs
3) It has broken the `ansible_default_ipv4` ansible fact, as the `ip` command is not present (this is based on my tests, not science or code, but I think the ip command is used for getting the fact
4) We are just going to be hunting for bugs as they come, increasing the maintenance costs
5) It is slightly less than 10% increase in size to have the standard Debian image instead of buster:slim. Is this even relevant nowadays? Even older computers have a great disk capacity and as far as speed of download goes, I think the speed up won't be major for majority of the people (the ones with bad internet connectivity are still going to be downloading 90% of the image just as slow)

**Comment by geerlingguy** [comment]
@fourstepper - I like the trimming in size as long as it's not too disruptive; it may not seem like too much, but 10% over the course of the 4-5 years this image is active isn't nothing.

But feel free to open a follow-up PR reverting this change and the man folder addition and I'll reconsider. It's 10% of the uncompressed size; compressed it's even a smaller difference.

**Comment by fourstepper** [comment]
@geerlingguy I have sent the PR just now - thank you for considering this. Once a person pulls the image, they usually don't update it that often to justify the maintenance price, I think.

All the best!

**Pull request merged**
